import Head from "next/head";
import Link from "next/link";
// import styles from '@/styles/Home.module.css'
import { NavBar, NavUl, NavLi } from "@/styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className={NavBar}>
        <ul>
          <li>
            <Link href={"/"}>Home</Link>
          </li>
          <li>
            <Link href={"/"}>News</Link>
          </li>
          <li>
            <Link href={"/"}>Review</Link>
          </li>
          <li>
            <Link href={"/"}>Contact us</Link>
          </li>
          <li>
            <Link href={"/about"}>About</Link>
          </li>
        </ul>
        <ul>
          <li>
            <Link href={"/"}>Log in</Link>
          </li>
          <li>
            <Link href={"/about"}>Sign in</Link>
          </li>
        </ul>

      </nav>
    </>
  );
}
